# Generated by Django 3.2.6 on 2022-05-28 09:31

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
