# Generated by Django 3.2.6 on 2022-05-28 10:15

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20220528_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=5000)),
        ),
    ]
